resolver: lts-9.6

packages:
- .

extra-deps: [
    distributed-process-0.6.6
  , distributed-process-extras-0.3.2
  , distributed-process-simplelocalnet-0.2.3.3
  , network-transport-0.4.4.0
  , network-transport-tcp-0.5.1
  , binary-0.8.3.0
  , syb-0.6
  , random-1.1
  , time-1.6.0.1
  , mtl-2.2.1
  , either-4.4.1.1
  , transformers-0.5.2.0
  ]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
